### ISSUE TITLE
Cannot render non-public classes.

### ISSUE THREAD

**Issue by mjfryc** [mjfryc/mjaron-etudes-java#19]
There is following error during rendering the non-public `Person` class:

```txt
Exception in thread "main" java.lang.RuntimeException: Render operation failed.
	at pl.mjaron.etudes.table.RenderOperation.execute(RenderOperation.java:62)
	at pl.mjaron.etudes.table.RenderContext.run(RenderContext.java:853)
	at MyClass.main(MyClass.java:51)
Caused by: java.lang.RuntimeException: Cannot obtain value of field: [name], of type: [class java.lang.String]: invocation of getter has failed.
	at pl.mjaron.etudes.Obj.visitFieldValues(Obj.java:100)
	at pl.mjaron.etudes.table.BeanTableSource$RowsIterator.next(BeanTableSource.java:113)
	at pl.mjaron.etudes.table.BeanTableSource$RowsIterator.next(BeanTableSource.java:87)
	at pl.mjaron.etudes.table.TableColumnsWidthDetector.compute(TableColumnsWidthDetector.java:58)
	at pl.mjaron.etudes.table.ColumnWidthResolver.resolve(ColumnWidthResolver.java:84)
	at pl.mjaron.etudes.table.RenderOperation.execute(RenderOperation.java:32)
	... 2 more
Caused by: java.lang.IllegalAccessException: class pl.mjaron.etudes.Obj cannot access a member of class Person with modifiers "public"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Method.invoke(Method.java:560)
	at pl.mjaron.etudes.Obj.visitFieldValues(Obj.java:97)
	... 7 more
```

Whole example:

```java
import java.util.Date;
import pl.mjaron.etudes.Table;
import pl.mjaron.etudes.table.VerticalAlign;

class Person {
    private final String name;
    private final String surname;
    private final Date birthday;
    private final String address;
    private final String contact;

    public Person(String name, String surname, Date birthday, String address, String contact) {
        this.name = name;
        this.surname = surname;
        this.birthday = birthday;
        this.address = address;
        this.contact = contact;
    }

    public String getName() {
        return name;
    }

    public String getSurname() {
        return surname;
    }

    public Date getBirthday() {
        return birthday;
    }

    public String getAddress() {
        return address;
    }

    public String getContact() {
        return contact;
    }

    public static Person[] getSampleData() {
        return new Person[]{
                new Person("Sally", "Fox", new Date(1972, 2, 25), "London", "sally@sallymfox.com"),
                new Person("Jay", "Elephant", new Date(1920, 2, 20), "Paris", "jay.elephant@protonmail.com"),
                new Person("Bella", "Tran", new Date(1963, 3, 12), "China", "tran@bella.com")
        };
    }
}

public class MyClass {
    public static void main(String args[]) {
      Table.render(Person.getSampleData(), Person.class).run();
    }
}
```

Tested with: <https://www.jdoodle.com/online-java-compiler-ide/>

**Comment by mjfryc** [comment]
So fix will be available with next release after `0.3.0`.
